// import "./globals.css";
"use client";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "@/components/app.header";
import Footer from "@/components/app.footer";
import Container from "react-bootstrap/Container";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>

        <Container style={{ minHeight: "calc(100vh - 106px" }}>
          {children}
        </Container>

        <Footer></Footer>
        <ToastContainer />
      </body>
    </html>
  );
}
