import type { Metadata } from "next";
export const metadata = {
  title: "Blogs Detail",
  description: "Generated by bla bla",
};

export default function BlogsDetailLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
